development:
  adapter: mysql
#  adapter: postgresql
#  encoding: unicode
  database: mapmill
  pool: 5
  username: mapmill 
  password: m4pm1ll 

test:
#  adapter: postgresql
  adapter: mysql
#  encoding: unicode
  database: mapmill_test 
  pool: 5
  username: mapmill 
  password: eene8ooH 

production:
  adapter: postgresql
#  encoding: unicode
  database: mapmill_prod
  pool: 5
  username: mapmill 
  password:  
